# Struktur Data pada NumPy
Struktur data utama dalam NumPy adalah array N-dimensi, yang juga dikenal sebagai ndarray. Ndarray merupakan kumpulan elemen dengan tipe data yang sama, yang diatur dalam bentuk N-dimensi (misalnya vektor, matriks, atau tensor).

<!-- (n-dimensional array) bisa digunakan untuk merepresentasikan vektor dan matriks, serta struktur data berdimensi lebih tinggi (misalnya tensor). Jadi, dalam hal ini, kita bisa mengatakan bahwa NumPy menggunakan struktur data yang bisa digunakan untuk merepresentasikan vektor dan matriks, tetapi itu bukan satu-satunya penggunaannya. -->

## Homogenitas

Homogenitas dalam konteks ndarray NumPy mengacu pada kenyataan bahwa semua elemen dalam sebuah array harus memiliki tipe data yang sama. Dalam struktur data ndarray, elemen-elemen yang memiliki tipe data yang berbeda tidak diperbolehkan. Hal ini membedakan ndarray dari struktur data Python lainnya, seperti list, yang memungkinkan elemen-elemen dengan tipe data yang berbeda.

Alasan homogenitas dalam ndarray penting adalah karena ini memungkinkan NumPy untuk menyimpan dan mengakses data secara lebih efisien. Dikarenakan semua elemen memiliki tipe data yang sama, NumPy dapat menyimpan data dalam blok memori yang kontigu dan melakukan operasi dengan lebih cepat daripada struktur data yang memungkinkan elemen dengan tipe data yang berbeda. Homogenitas juga memudahkan dalam melakukan operasi matematika pada array, karena operasi tersebut memerlukan konsistensi tipe data untuk menghasilkan hasil yang benar dan konsisten.

Sebagai contoh, berikut ini adalah pembuatan ndarray yang homogen:

In [1]:
import numpy as np

# Membuat array dengan elemen bertipe integer
a = np.array([1, 2, 3, 4, 5], dtype=int)

# Membuat array dengan elemen bertipe float
b = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=float)

Dalam contoh-contoh di atas, semua elemen dalam masing-masing array memiliki tipe data yang sama, yaitu integer atau float. Homogenitas tipe data dalam ndarray NumPy memastikan efisiensi dan konsistensi dalam operasi yang melibatkan array.

## Ukuran tetap

Ukuran tetap dalam konteks ndarray NumPy mengacu pada kenyataan bahwa ukuran (jumlah elemen dan bentuk) dari sebuah array tidak dapat diubah setelah array tersebut dibuat. Dalam struktur data ndarray, setelah Anda menentukan jumlah elemen dan bentuk (shape) array, Anda tidak dapat mengubahnya secara langsung.

Alasan ukuran tetap dalam ndarray penting adalah karena ini memungkinkan NumPy untuk mengelola memori secara lebih efisien. Ketika Anda membuat sebuah array, NumPy mengalokasikan blok memori yang tepat untuk menyimpan elemen-elemen array. Jika ukuran array diizinkan untuk berubah secara dinamis, seperti dalam struktur data Python seperti list, maka pengelolaan memori akan menjadi lebih kompleks dan potensi pengurangan kinerja akan terjadi.

Jika Anda ingin mengubah ukuran atau bentuk array, Anda harus membuat array baru dengan ukuran atau bentuk yang diinginkan, lalu mengkopi data dari array lama ke array baru. Anda juga dapat menggunakan fungsi seperti numpy.reshape() untuk mengubah bentuk array tanpa mengubah jumlah elemen.

Sebagai contoh, berikut ini adalah pembuatan ndarray dengan ukuran tetap:

In [2]:
import numpy as np

# Membuat array 1D dengan 5 elemen
a = np.array([1, 2, 3, 4, 5])

# Membuat array 2D dengan 9 elemen (3x3)
b = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Membuat array 3D dengan 8 elemen (2xx2x2)
c = np.array([[[1, 2], 
               [3, 4]], 
              [[5, 6], 
               [7, 8]]])

In [3]:
import numpy as np
b = np.array([[1, 2], 
              [4, 5], 
              [7, 8]])
b.shape

(3, 2)

<!-- Dimensi array ini adalah 3, karena memiliki 3 level: 2 blok, setiap blok berisi 2 baris, dan setiap baris berisi 2 kolom. Anda bisa memverifikasi ini dengan c.ndim.

Jumlah elemen dalam array ini adalah 8, karena terdapat 2 blok, 2 baris dalam setiap blok, dan 2 kolom dalam setiap baris (2 * 2 * 2 = 8). Anda bisa memverifikasi ini dengan c.size. -->

Dalam contoh di atas, array a memiliki 5 elemen dan array b memiliki 9 elemen. Anda tidak dapat menambahkan atau mengurangi elemen dalam array ini secara langsung. Namun, Anda dapat membuat array baru dengan ukuran yang berbeda atau mengubah bentuk array menggunakan fungsi seperti numpy.reshape().

## Efisien

Efisien dalam konteks ndarray NumPy mengacu pada kemampuan struktur data ndarray untuk menyimpan dan memanipulasi data secara lebih efisien daripada struktur data bawaan Python seperti list atau tuple. Efisiensi ini dicapai melalui beberapa aspek desain dan implementasi ndarray, yang mencakup:

- Penyimpanan data yang kontigu: Ndarray menyimpan data dalam blok memori yang kontigu, yang berarti elemen-elemen dalam array disimpan berdampingan dalam memori. Hal ini memungkinkan NumPy untuk mengakses dan memanipulasi data dengan lebih cepat daripada struktur data seperti list, yang menyimpan data secara tidak kontigu.

- Homogenitas tipe data: Seperti yang telah dijelaskan sebelumnya, semua elemen dalam ndarray harus memiliki tipe data yang sama. Homogenitas ini memudahkan NumPy untuk mengoptimalkan operasi dan perhitungan pada array, karena ia hanya perlu mempertimbangkan satu tipe data dalam operasi tersebut.

- Operasi vektorisasi: NumPy mendukung operasi vektorisasi, yang memungkinkan Anda untuk melakukan operasi pada seluruh array sekaligus, tanpa perlu menggunakan loop. Vektorisasi memungkinkan NumPy untuk memanfaatkan optimasi pada tingkat prosesor dan mempercepat operasi pada array.

- Fungsi universal (ufunc): NumPy menyediakan banyak fungsi universal yang dirancang khusus untuk bekerja dengan ndarray secara efisien. Fungsi-fungsi ini diimplementasikan dalam bahasa C atau Fortran untuk memastikan kinerja yang tinggi dan dikompilasi secara statis ke dalam pustaka NumPy.

Contoh efisiensi NumPy dalam operasi:

In [3]:
import numpy as np

# Membuat array NumPy
a = np.array([1, 2, 3, 4, 5])

# Melakukan operasi penambahan pada seluruh elemen array tanpa menggunakan loop
b = a + 10

print(b)  # Output: array([11, 12, 13, 14, 15])

[11 12 13 14 15]


Dalam contoh di atas, kita menambahkan 10 ke setiap elemen dalam array a tanpa perlu menggunakan loop. NumPy secara otomatis melakukan operasi ini secara vektorisasi dan menghasilkan array baru b. Efisiensi yang dicapai melalui desain dan implementasi ndarray memungkinkan NumPy untuk melakukan operasi ini dengan sangat cepat dan mengurangi overhead yang biasanya terkait dengan loop dalam Python.

## Universal Function

Fungsi universal (ufunc) dalam konteks ndarray NumPy adalah fungsi yang dirancang khusus untuk bekerja dengan array secara efisien. Fungsi universal mengambil satu atau beberapa input ndarray dan menghasilkan output ndarray. Ufunc dirancang untuk memproses array elemen-demi-elemen, dan mengaplikasikan operasi yang didefinisikan pada setiap elemen secara vektorisasi. Vektorisasi mengacu pada teknik di mana operasi dilakukan pada seluruh array sekaligus, tanpa perlu menggunakan loop.

Fungsi universal menyediakan beberapa keuntungan:

- Kinerja: Ufunc diimplementasikan dalam bahasa C atau Fortran, yang menyediakan kinerja yang lebih baik daripada operasi ekuivalen yang ditulis dalam Python murni. Dengan mengkompilasi ufunc ke dalam pustaka NumPy, mereka dapat memanfaatkan optimasi pada tingkat prosesor dan mempercepat operasi pada array.

- Kemudahan penggunaan: Karena ufunc bekerja secara otomatis pada elemen array, Anda tidak perlu menulis loop untuk mengaplikasikan operasi pada setiap elemen array. Hal ini membuat kode Anda lebih mudah dibaca dan lebih pendek.

- Konsistensi: Ufunc menyediakan konsistensi dalam operasi pada array, karena mereka dirancang untuk bekerja dengan ndarray dengan cara yang sama, terlepas dari tipe data atau bentuk array.

Beberapa contoh fungsi universal yang umum digunakan dalam NumPy meliputi:

- Operasi aritmatika: np.add(), np.subtract(), np.multiply(), np.divide(), dll.
- Operasi trigonometri: np.sin(), np.cos(), np.tan(), dll.
- Operasi logaritma: np.log(), np.log10(), np.log2(), dll.
- Operasi perbandingan: np.greater(), np.less(), np.equal(), dll.

Contoh penggunaan fungsi universal:

In [4]:
import numpy as np

# Membuat array NumPy
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Menggunakan fungsi universal np.add() untuk menambahkan elemen a dan b
c = np.add(a, b)

print(c)  # Output: array([6, 6, 6, 6, 6])

# Menggunakan fungsi universal np.sin() pada array a
d = np.sin(a)

print(d)  # Output: array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

[6 6 6 6 6]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


Dalam contoh di atas, kita menggunakan fungsi universal np.add() untuk menambahkan elemen array a dan b, dan np.sin() untuk menghitung sinus dari setiap elemen dalam array a. Operasi ini dilakukan secara vektorisasi dan menghasilkan output ndarray.

# Soal Vector & Matrix  pada NumPy

Berikut ini adalah lima soal yang mencakup Homogenitas, Ukuran tetap, Efisien, dan Fungsi universal dalam konteks NumPy:

### Soal 1: Homogenitas - Vektor
Diberikan dua vektor dalam bentuk list Python:

In [5]:
vector_a = [1, 2, 3]
vector_b = [1, 2, 'tiga']

Manakah di antara kedua vektor ini yang dapat dikonversi menjadi ndarray NumPy yang homogen? Jelaskan mengapa atau mengapa tidak.

In [8]:
# Jawab soal 1 
Yang dapat dikonversi menjadi ndarray Numpy adalah vector_a, hal itu dikarenakan dalam suatu array numpy sebaiknya memiliki tipe data yang sama.
Pada vector_a tipe data berupa interger, sedangkan pada vector_b terdapat dua tipe data yakni interger dan string. 

### Soal 2: Homogenitas - Matriks
Diberikan matriks dalam bentuk list Python:

In [7]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 'delapan', 9]
]

In [ ]:
# Jawab soal 2
Tidak dapat dikonversi menjadi ndarray Numpy karena pada pada salah satu elemennya memiliki tipe data string (berbeda dengan data yang lainnya yang berupa interger).

Apakah matriks ini dapat dikonversi menjadi ndarray NumPy yang homogen? Jelaskan mengapa atau mengapa tidak.

### Soal 3: Ukuran tetap - Vektor
Diberikan sebuah vektor ndarray NumPy:

In [9]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5, 6])
vector

array([1, 2, 3, 4, 5, 6])

In [12]:
# Jawab soal 3
# Menggunakan reshape untuk mengubah bentuk array menjadi 2D
vector_2d = vector.reshape((2, 3))

print('\nArray setelah reshape:')
print(vector_2d)
print("shape:", vector_2d.shape)


Array setelah reshape:
[[1 2 3]
 [4 5 6]]
shape: (2, 3)


Bagaimana Anda akan mengubah bentuk (reshape) vektor ini menjadi matriks 2D berukuran 2x3 tanpa mengubah jumlah elemennya?

### Soal 4: Ukuran tetap - Matriks
Diberikan sebuah matriks ndarray NumPy:

In [22]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

Bagaimana Anda akan mengubah bentuk (reshape) matriks ini menjadi tensor 3D berukuran 2x1x3 tanpa mengubah jumlah elemennya?

In [24]:
# Jawab soal 4
# Menggunakan reshape untuk mengubah bentuk array menjadi 3D
matrix_3d = np.reshape(matrix, (2, 1, 3))

print('\nArray setelah reshape:')
print(matrix_3d)
print("shape:", matrix_3d.shape)


Array setelah reshape:
[[[1 2 3]]

 [[4 5 6]]]
shape: (2, 1, 3)


### Soal 5: Efisien - Vektor
Diberikan sebuah vektor ndarray NumPy:

In [25]:
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
vector

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Tunjukkan bagaimana Anda akan mengalikan setiap elemen vektor ini dengan 3 secara efisien, tanpa menggunakan loop.

In [26]:
# Jawab
c = vector * 3
print("vector * 3:", c)

vector * 3: [ 3  6  9 12 15 18 21 24 27]


### Soal 6: Efisien - Matriks
Diberikan sebuah matriks ndarray NumPy:

In [27]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Tunjukkan bagaimana Anda akan mengalikan setiap elemen matriks ini dengan 4 secara efisien, tanpa menggunakan loop.

In [28]:
# Jawab
c = matrix * 4
print("matrix * 4:", c)

matrix * 4: [[ 4  8 12]
 [16 20 24]
 [28 32 36]]


### Soal 7: Fungsi universal - Vektor
Diberikan sebuah vektor ndarray NumPy:

In [29]:
import numpy as np
vector = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
vector

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

Gunakan fungsi universal untuk menghitung sinus dan kosinus dari setiap elemen dalam vektor ini, lalu simpan hasilnya dalam dua vektor baru.

In [31]:
# Jawab
a = np.sin(vector)
print("sin(vector):", a)

b = np.cos(vector)
print("cos(vector):", b)

sin(vector): [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
cos(vector): [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00]


### Soal 8: Fungsi universal - Matriks
Diberikan sebuah matriks ndarray NumPy:

In [33]:
matrix = np.array([
    [0, np.pi/4, np.pi/2],
    [3*np.pi/4, np.pi, 5*np.pi/4],
    [3*np.pi/2, 7*np.pi/4, 2*np.pi]
])
matrix

array([[0.        , 0.78539816, 1.57079633],
       [2.35619449, 3.14159265, 3.92699082],
       [4.71238898, 5.49778714, 6.28318531]])

Gunakan fungsi universal untuk menghitung sinus dan kosinus dari setiap elemen dalam matriks ini, lalu simpan hasilnya dalam dua matriks baru.

In [34]:
# Jawab
c = np.sin(matrix)
print("sin(matrix):", c)

d = np.cos(matrix)
print("cos(matrix):", d)

sin(matrix): [[ 0.00000000e+00  7.07106781e-01  1.00000000e+00]
 [ 7.07106781e-01  1.22464680e-16 -7.07106781e-01]
 [-1.00000000e+00 -7.07106781e-01 -2.44929360e-16]]
cos(matrix): [[ 1.00000000e+00  7.07106781e-01  6.12323400e-17]
 [-7.07106781e-01 -1.00000000e+00 -7.07106781e-01]
 [-1.83697020e-16  7.07106781e-01  1.00000000e+00]]


# Atribut dan Fungsi pada NumPy Python

Mari kita gunakan analogi mobil untuk menjelaskan perbedaan antara atribut dan fungsi dalam konteks Numpy atau pemrograman berorientasi objek pada umumnya.

Bayangkan bahwa Anda memiliki mobil. Mobil tersebut memiliki berbagai ***atribut***, seperti warna, merek, model, dan tahun pembuatan. Ini semacam data atau informasi yang melekat pada mobil tersebut dan menggambarkan sifat atau karakteristiknya.

Di sisi lain, mobil tersebut juga memiliki berbagai ***fungsi*** atau ***metode***. Ini adalah tindakan yang dapat dilakukan oleh mobil, seperti 'berjalan', 'berhenti', 'belok', dan 'klakson'. Fungsi atau metode ini memanipulasi atribut dari mobil atau melakukan tindakan lain yang berhubungan dengannya.

Dalam konteks Numpy, atribut dan fungsi berlaku secara serupa. Misalnya, kita memiliki array Numpy:

In [19]:
# Membuat array numpy
arr = np.array([1, 2, 3, 4, 5])

Di sini, arr adalah objek array Numpy. Ini memiliki berbagai atribut, seperti shape, size, dan dtype, yang masing-masing menggambarkan bentuk array, jumlah elemen dalam array, dan tipe data elemen dalam array.

In [20]:
print(arr.shape)  # atribut shape
print(arr.size)  # atribut size
print(arr.dtype)  # atribut dtype

(5,)
5
int32


Array Numpy juga memiliki berbagai fungsi atau metode, seperti mean(), min(), dan max(), yang masing-masing menghitung rata-rata elemen dalam array, nilai minimum dalam array, dan nilai maksimum dalam array.

In [21]:
print(arr.mean())  # fungsi mean
print(arr.min())  # fungsi min
print(arr.max())  # fungsi max

3.0
1
5


Jadi, perbedaan utama antara atribut dan fungsi adalah bahwa atribut adalah karakteristik atau properti dari objek, sedangkan fungsi atau metode adalah tindakan yang dapat dilakukan oleh objek.

# Atribut Array
Setiap array NumPy memiliki beberapa atribut penting yang dapat memberikan informasi tentang array tersebut. Atribut-atribut ini meliputi:

- shape: Atribut ini mengembalikan ukuran array dalam bentuk tuple. Misalnya, jika array memiliki 2 baris dan 3 kolom, maka shape akan menghasilkan (2, 3).

- ndim: Atribut ini mengembalikan jumlah dimensi array. Sebagai contoh, jika array adalah 1D (vektor), maka ndim akan menghasilkan 1, dan jika array adalah 2D (matriks), maka ndim akan menghasilkan 2.

- size: Atribut ini mengembalikan jumlah elemen dalam array. Jumlah ini sama dengan hasil perkalian semua elemen dalam tuple shape.

- dtype: Atribut ini mengembalikan tipe data elemen dalam array. Tipe data umum yang digunakan dalam array NumPy meliputi int32, int64, float32, dan float64. Tipe data ini tergantung pada sistem operasi dan data yang disimpan dalam array.

Contoh Kode Atribut Array:

In [22]:
# Membuat array 2D
a = np.array([[1, 2, 3], [4, 5, 6]])
# Menampilkan atribut shape, ndim, size, dan dtype
print("shape:", a.shape)  # Output: (2, 3)
print("ndim:", a.ndim)    # Output: 2
print("size:", a.size)    # Output: 6
print("dtype:", a.dtype)  # Output: int64 (tergantung pada sistem operasi)

shape: (2, 3)
ndim: 2
size: 6
dtype: int32


Dengan memahami atribut-atribut ini, Anda dapat lebih mudah dalam mengelola dan memahami struktur array NumPy ketika bekerja dengan data dalam berbagai dimensi dan ukuran.

## Berikut penjelasan lebih rinci dan contoh untuk setiap atribut array NumPy:

### Shape
`shape`: Atribut ini mengembalikan ukuran array dalam bentuk tuple. Angka dalam tuple menunjukkan jumlah elemen di sepanjang setiap sumbu.

Contoh:

In [23]:
# Array 1D
a = np.array([1, 2, 3])
print("shape:", a.shape)  # Output: (3,)

# Array 2D
b = np.array([[1, 2, 3], 
              [4, 5, 6]])
print("shape:", b.shape)  # Output: (2, 3)

shape: (3,)
shape: (2, 3)


### ndim
`ndim`: Atribut ini mengembalikan jumlah dimensi array. Jumlah dimensi menunjukkan seberapa "dalam" struktur array.

Contoh:

In [24]:
# Array 1D
a = np.array([1, 2, 3])
print("ndim:", a.ndim)  # Output: 1

# Array 2D
b = np.array([[1, 2, 3], 
              [4, 5, 6]])
print("ndim:", b.ndim)  # Output: 2

ndim: 1
ndim: 2


### size
`size`: Atribut ini mengembalikan jumlah elemen dalam array. Jumlah ini sama dengan hasil perkalian semua elemen dalam tuple shape.

Contoh:

In [25]:
# Array 1D
a = np.array([1, 2, 3])
print("size:", a.size)  # Output: 3

# Array 2D
b = np.array([[1, 2, 3], 
              [4, 5, 6]])
print("size:", b.size)  # Output: 6

size: 3
size: 6


### dtype
`dtype`: Atribut ini mengembalikan tipe data elemen dalam array. Tipe data ini tergantung pada sistem operasi dan data yang disimpan dalam array. Beberapa tipe data umum yang digunakan dalam array NumPy meliputi int32, int64, float32, dan float64.

Contoh:

In [26]:
import numpy as np

# Array 1D dengan tipe data integer
a = np.array([1, 2, 3])
print("dtype:", a.dtype)  # Output: int64 (tergantung pada sistem operasi)

# Array 1D dengan tipe data float
b = np.array([1.0, 2.0, 3.0])
print("dtype:", b.dtype)  # Output: float64

# Array 1D dengan tipe data yang ditentukan secara eksplisit
c = np.array([1, 2, 3], dtype=np.float32)
print("dtype:", c.dtype)  # Output: float32

dtype: int32
dtype: float64
dtype: float32


# Reshape Array

Reshape adalah sebuah operasi dalam NumPy yang memungkinkan kita untuk mengubah bentuk atau dimensi dari sebuah array tanpa merubah data yang ada di dalamnya. Ini sangat berguna dalam berbagai situasi dimana kita perlu mengubah dimensi array untuk memenuhi kebutuhan algoritma atau operasi tertentu.

Berikut adalah contoh penggunaan metode reshape:



In [10]:
import numpy as np

# Membuat array 1D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print('Array asli:')
print(arr)

# Menggunakan reshape untuk mengubah bentuk array menjadi 2D
arr_2d = arr.reshape((4, 2))

print('\nArray setelah reshape:')
print(arr_2d)

Array asli:
[1 2 3 4 5 6 7 8]

Array setelah reshape:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Pada contoh di atas, array asli berdimensi 1 (vektor) diubah bentuknya menjadi array 2D dengan 4 baris dan 2 kolom menggunakan metode reshape.

Ada beberapa hal yang perlu diperhatikan saat menggunakan reshape:

- Jumlah elemen dalam array sebelum dan sesudah operasi reshape harus sama. Dalam contoh di atas, array asli memiliki 8 elemen dan array hasil reshape juga memiliki 8 elemen (4 baris x 2 kolom).

- Anda bisa menggunakan nilai -1 pada salah satu dimensi saat melakukan reshape dan NumPy akan menghitung dimensi tersebut secara otomatis. Misalnya, arr.reshape((-1, 2)) akan menghasilkan array 2D dengan jumlah kolom 2 dan jumlah baris dihitung secara otomatis oleh NumPy.

Contoh penggunaan -1 dalam reshape:

In [14]:
import numpy as np

# Membuat array 1D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print('Array asli:')
print(arr)

# Menggunakan reshape dengan -1
arr_2d = arr.reshape((2, -1))

print('\nArray setelah reshape:')
print(arr_2d)


Array asli:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Array setelah reshape:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Pada contoh di atas, array asli berdimensi 1 (vektor) diubah bentuknya menjadi array 2D dengan 2 baris dan jumlah kolom dihitung otomatis oleh NumPy. Karena jumlah total elemen adalah 12, maka jumlah kolom setelah reshape menjadi 6.

# Convert 1D to 2D

***Mengubah 1D ke 2D Menggunakan np.newaxis dan np.expand_dims***

`np.newaxis` dan `np.expand_dims` adalah dua metode yang bisa digunakan untuk menambah dimensi ke sebuah array di numpy. Kedua metode ini sangat berguna ketika kita ingin mengubah array 1 dimensi (1D) menjadi array 2 dimensi (2D) atau ketika kita ingin menambah dimensi tambahan ke array yang sudah ada.

**1. np.newaxis**

`np.newaxis` digunakan untuk menambahkan sumbu/axis kosong ke array yang ada. Misalnya, jika kita memiliki array 1D dengan bentuk `(n,)`, kita bisa menggunakan `np.newaxis` untuk mengubah bentuknya menjadi `(n, 1)` (2D kolom vektor) atau `(1, n)` (2D baris vektor).

Berikut adalah contoh penggunaannya:

In [15]:
import numpy as np

# Buat array 1D
arr = np.array([1, 2, 3, 4, 5])

# Ubah ke 2D menggunakan np.newaxis
arr_2d_col = arr[:, np.newaxis]  # kolom vektor
arr_2d_row = arr[np.newaxis, :]  # baris vektor

print("Original array shape:", arr.shape)
print("2D column vector shape:", arr_2d_col.shape)
print("2D row vector shape:", arr_2d_row.shape)

Original array shape: (5,)
2D column vector shape: (5, 1)
2D row vector shape: (1, 5)


In [18]:
print(arr_2d_col)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [19]:
print(arr_2d_row)

[[1 2 3 4 5]]


**2. np.expand_dims**

`np.expand_dims` berfungsi mirip dengan `np.newaxis`, tetapi ia memiliki sintaks yang lebih eksplisit. `np.expand_dims` mengambil dua argumen, yaitu array yang akan diubah dan posisi sumbu baru.

In [16]:
import numpy as np

# Buat array 1D
arr = np.array([1, 2, 3, 4, 5])

# Ubah ke 2D menggunakan np.expand_dims
arr_2d_col = np.expand_dims(arr, axis=1)  # kolom vektor
arr_2d_row = np.expand_dims(arr, axis=0)  # baris vektor

print("Original array shape:", arr.shape)
print("2D column vector shape:", arr_2d_col.shape)
print("2D row vector shape:", arr_2d_row.shape)

Original array shape: (5,)
2D column vector shape: (5, 1)
2D row vector shape: (1, 5)


In [17]:
arr_2d_col

array([[1],
       [2],
       [3],
       [4],
       [5]])

Dalam kedua contoh di atas, kita berhasil mengubah array 1D menjadi array 2D menggunakan `np.newaxis` dan `np.expand_dims`. Dalam konteks tertentu, menggunakan `np.expand_dims` bisa lebih jelas dan eksplisit daripada menggunakan `np.newaxis`, terutama ketika bekerja dengan array yang memiliki lebih dari 2 dimensi.

# Membuat Array Khusus

numpy.zeros(): Fungsi ini membuat array dengan semua elemen bernilai 0. Anda perlu menyediakan bentuk array yang diinginkan sebagai argumen.

Contoh:

In [27]:
import numpy as np

# Membuat array 2x3 dengan elemen 0
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


numpy.ones(): Fungsi ini membuat array dengan semua elemen bernilai 1. Anda perlu menyediakan bentuk array yang diinginkan sebagai argumen.

Contoh:

In [28]:
import numpy as np

# Membuat array 2x3 dengan elemen 1
ones = np.ones((2, 3))
print(ones)


[[1. 1. 1.]
 [1. 1. 1.]]


numpy.full(): Fungsi ini membuat array dengan semua elemen bernilai sama. Anda perlu menyediakan bentuk array yang diinginkan dan nilai elemen yang diinginkan sebagai argumen.

Contoh:

In [29]:
import numpy as np

# Membuat array 2x3 dengan elemen 7
full = np.full((2, 3), 7)
print(full)


[[7 7 7]
 [7 7 7]]


numpy.eye(): Fungsi ini membuat matriks identitas dengan ukuran yang ditentukan. Matriks identitas adalah matriks persegi dengan angka 1 pada diagonal dan angka 0 pada elemen lainnya.

Contoh:

In [30]:
import numpy as np

# Membuat matriks identitas 3x3
eye = np.eye(3)
print(eye)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


numpy.arange(): Fungsi ini membuat array dengan rentang angka spesifik. Anda perlu menyediakan nilai awal, nilai akhir, dan langkah sebagai argumen.

Contoh:

In [31]:
import numpy as np

# Membuat array dengan rentang angka 0 hingga 9 (tidak termasuk 10), dengan langkah 1
arange = np.arange(0, 10, 1)
print(arange)


[0 1 2 3 4 5 6 7 8 9]


numpy.linspace(): Fungsi ini membuat array dengan jumlah angka yang sama antara dua nilai. Anda perlu menyediakan nilai awal, nilai akhir, dan jumlah elemen yang diinginkan sebagai argumen.

Contoh:

In [32]:
import numpy as np

# Membuat array dengan 5 angka, sama jarak antara 0 dan 1
linspace = np.linspace(0, 1, 5)
print(linspace)


[0.   0.25 0.5  0.75 1.  ]


Dengan memahami cara membuat array khusus ini, Anda dapat menghasilkan data awal untuk berbagai kasus penggunaan, seperti inisialisasi bobot dalam machine learning atau menghasilkan data testing.

# Operasi Matematika pada Array
NumPy menyediakan berbagai operasi matematika dan aritmatika yang dapat dilakukan pada array. Beberapa operasi dasar yang dapat Anda lakukan meliputi:

Penjumlahan dan Pengurangan Array anda dapat menjumlahkan dan mengurangkan array dengan ukuran yang sama dengan menggunakan operator + dan -.
Contoh:

In [33]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Penjumlahan array
c = a + b
print("a + b:", c)

# Pengurangan array
d = a - b
print("a - b:", d)


a + b: [5 7 9]
a - b: [-3 -3 -3]


Perkalian dan Pembagian Array: Anda dapat mengalikan dan membagi elemen dalam array dengan menggunakan operator * dan /.

Contoh:

In [34]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Perkalian elemen array
c = a * b
print("a * b:", c)

# Pembagian elemen array
d = a / b
print("a / b:", d)


a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]


Operasi skalar: Anda dapat melakukan operasi aritmatika dengan skalar (angka tunggal) dan array. Operasi ini akan diterapkan pada setiap elemen array.

Contoh:

In [35]:
import numpy as np

a = np.array([1, 2, 3])

# Menambahkan skalar ke array
b = a + 5
print("a + 5:", b)

# Mengalikan array dengan skalar
c = a * 2
print("a * 2:", c)


a + 5: [6 7 8]
a * 2: [2 4 6]


Fungsi matematika: NumPy menyediakan berbagai fungsi matematika yang dapat diterapkan pada array, seperti numpy.exp(), numpy.sqrt(), dan numpy.sin().

Contoh:

In [36]:
import numpy as np

a = np.array([1, 2, 3])

# Menghitung eksponensial setiap elemen array
b = np.exp(a)
print("exp(a):", b)

# Menghitung akar kuadrat setiap elemen array
c = np.sqrt(a)
print("sqrt(a):", c)

# Menghitung sinus setiap elemen array
d = np.sin(a)
print("sin(a):", d)


exp(a): [ 2.71828183  7.3890561  20.08553692]
sqrt(a): [1.         1.41421356 1.73205081]
sin(a): [0.84147098 0.90929743 0.14112001]


Agregasi: Anda dapat menghitung statistik agregat pada array, seperti jumlah, rata-rata, dan nilai maksimum dengan menggunakan fungsi seperti numpy.sum(), numpy.mean(), dan numpy.max().

Contoh:

In [37]:
import numpy as np

a = np.array([1, 2, 3])

# Menghitung jumlah elemen array
total = np.sum(a)
print("sum(a):", total)

# Menghitung rata-rata elemen array
mean = np.mean(a)
print("mean(a):", mean)

# Menghitung nilai maksimum dalam array
max_value = np.max(a)
print("max(a):", max_value)


sum(a): 6
mean(a): 2.0
max(a): 3


## Specify the axis

**Operasi Matematika pada Array 1D**

Misalnya, kita bisa melakukan penjumlahan, pengurangan, perkalian, dan pembagian antara array 1D dengan mudah.


In [98]:
import numpy as np

# Membuat dua array 1D
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Melakukan operasi matematika
print("Penjumlahan: ", arr1 + arr2)
print("Pengurangan: ", arr1 - arr2)
print("Perkalian: ", arr1 * arr2)
print("Pembagian: ", arr1 / arr2)

Penjumlahan:  [ 6  8 10 12]
Pengurangan:  [-4 -4 -4 -4]
Perkalian:  [ 5 12 21 32]
Pembagian:  [0.2        0.33333333 0.42857143 0.5       ]


**Operasi Matematika pada Array 2D**

Operasi matematika juga bisa dilakukan pada array 2D. Anda bisa melakukan operasi aritmatika antara dua array 2D dengan bentuk yang sama.

In [99]:
# Membuat dua array 2D
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Melakukan operasi matematika
print("Penjumlahan: \n", arr1 + arr2)
print("Pengurangan: \n", arr1 - arr2)
print("Perkalian: \n", arr1 * arr2)
print("Pembagian: \n", arr1 / arr2)

Penjumlahan: 
 [[ 6  8]
 [10 12]]
Pengurangan: 
 [[-4 -4]
 [-4 -4]]
Perkalian: 
 [[ 5 12]
 [21 32]]
Pembagian: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


**Spesifikasi Axis pada Array 2D**

NumPy juga memungkinkan Anda untuk menentukan axis mana yang harus digunakan saat melakukan operasi pada array 2D. ***Axis 0 merujuk ke arah baris (vertikal), dan axis 1 merujuk ke arah kolom (horizontal).***

Berikut adalah contoh penggunaan axis pada operasi sum:

In [101]:
# Membuat array 2D
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Melakukan penjumlahan pada axis 0 (menjumlahkan setiap kolom)
print("Penjumlahan pada axis 0: ", arr.sum(axis=0))

# Melakukan penjumlahan pada axis 1 (menjumlahkan setiap baris)
print("Penjumlahan pada axis 1: ", arr.sum(axis=1))

Penjumlahan pada axis 0:  [5 7 9]
Penjumlahan pada axis 1:  [ 6 15]


In [102]:
arr.shape

(2, 3)

Demikian juga, kita bisa menggunakan axis pada operasi lain seperti `mean`, `min`, `max`, dll.

In [103]:
# Menghitung mean pada axis 0
print("Mean pada axis 0: ", arr.mean(axis=0))

# Menghitung min pada axis 1
print("Min pada axis 1: ", arr.min(axis=1))

Mean pada axis 0:  [2.5 3.5 4.5]
Min pada axis 1:  [1 4]


Harap diingat bahwa ketika kita melakukan operasi pada suatu axis, dimensi tersebut akan hilang dari bentuk array. Misalnya, jika kita melakukan `arr.sum(axis=0)` pada array dengan bentuk `(3, 2)`, hasilnya akan berbentuk `(2,)` karena kita melakukan operasi sepanjang axis 0 dan menghilangkan dimensi tersebut.

# Operasi Aljabar Linear
NumPy menyediakan modul numpy.linalg yang berisi berbagai fungsi untuk melakukan operasi aljabar linear pada array. Beberapa fungsi penting dalam modul ini meliputi:

Penjumlahan Matriks: Anda dapat menjumlahkan matriks dengan ukuran yang sama dengan menggunakan operator +.

Contoh:

In [38]:
import numpy as np

A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# Penjumlahan matriks
C = A + B
print(C)


[[ 6  8]
 [10 12]]


Perkalian Matriks: Anda dapat mengalikan dua matriks yang sesuai dengan menggunakan fungsi numpy.dot() atau operator @.

Contoh:

In [39]:
import numpy as np

A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# Perkalian matriks menggunakan numpy.dot()
C = np.dot(A, B)
print(C)

# Perkalian matriks menggunakan operator @
D = A @ B
print(D)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Transpose Matriks: Anda dapat mentranspose matriks (menukar baris dan kolom) dengan menggunakan atribut T atau fungsi numpy.transpose().

Contoh:

In [40]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

# Transpose matriks menggunakan atribut T
B = A.T
print(B)

# Transpose matriks menggunakan numpy.transpose()
C = np.transpose(A)
print(C)


[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


# Add, Remove, and Sort (Menambahkan, Menghapus, dan Mengurutkan Elemen)

**Menambahkan Elemen**

Dalam numpy, Anda bisa menambahkan elemen ke array menggunakan fungsi `numpy.append()`. Berikut contohnya:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Sebelum ditambahkan elemen: ", arr)
    
arr = np.append(arr, [6, 7, 8])
print("Setelah ditambahkan elemen: ", arr)

**Menghapus Elemen**

Anda bisa menggunakan fungsi `numpy.delete()` untuk menghapus elemen dari array. Berikut contohnya:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Sebelum dihapus elemen: ", arr)

arr = np.delete(arr, 2)
print("Setelah dihapus elemen: ", arr)

**Mengurutkan Elemen**

Anda bisa mengurutkan elemen dalam array menggunakan fungsi `numpy.sort()`. Berikut contohnya:

In [ ]:
arr = np.array([5, 2, 3, 1, 4])
print("Sebelum diurutkan: ", arr)

arr = np.sort(arr)
print("Setelah diurutkan: ", arr)

Pada setiap operasi, pastikan Anda memahami bahwa operasi tersebut tidak mengubah array asli, tetapi menghasilkan array baru. Jika Anda ingin operasi tersebut mengubah array asli, Anda harus menugaskan hasilnya kembali ke variabel array tersebut.

# Indexing dan Slicing
Dalam NumPy, Anda dapat mengakses elemen-elemen dalam array menggunakan indeks dan melakukan slicing untuk mengambil sebagian dari array. Berikut beberapa konsep dasar tentang indexing dan slicing pada array NumPy:

## Indexing

Indexing: Anda dapat mengakses elemen array berdasarkan indeksnya, yang dimulai dari 0. Pada array multidimensi, Anda menggunakan tanda koma untuk memisahkan indeks setiap dimensi.

Contoh:

In [41]:
import numpy as np

# Contoh 1D:
a = np.array([1, 2, 3, 4, 5])

# Mengakses elemen pada indeks 0
print(a[0])

#Contoh 2D:
b = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Mengakses elemen pada baris 1, kolom 2
print(b[1, 2])


1
6


Slicing: Anda dapat mengambil sebagian dari array dengan menggunakan slicing. Slicing menggunakan notasi [start:stop:step], di mana start adalah indeks awal (inklusif), stop adalah indeks akhir (eksklusif), dan step adalah jarak antara elemen.

Contoh:

In [42]:
import numpy as np

#Contoh 1D:
a = np.array([1, 2, 3, 4, 5])

# Mengambil elemen dari indeks 1 hingga 4 (eksklusif)
print(a[1:4])

# Contoh 2D:
b = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Mengambil baris 0 hingga 2 (eksklusif) dan kolom 1 hingga 3 (eksklusif)
print(b[0:2, 1:3])


[2 3 4]
[[2 3]
 [5 6]]


Indexing dan slicing dengan boolean: Anda juga dapat melakukan indexing dan slicing dengan menggunakan array boolean sebagai mask. Ini memungkinkan Anda untuk memilih elemen yang memenuhi kondisi tertentu.

Contoh:

In [43]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

# Membuat mask boolean untuk elemen yang lebih besar dari 2
mask = a > 2
print(mask)

# Menggunakan mask boolean untuk mengambil elemen yang lebih besar dari 2
print(a[mask])

[False False  True  True  True]
[3 4 5]


Dengan memahami teknik indexing dan slicing ini, Anda dapat mengakses dan memanipulasi bagian tertentu dari array NumPy dengan mudah. Hal ini sangat penting dalam analisis data, pemrosesan sinyal, dan berbagai aplikasi lain yang melibatkan manipulasi data dalam bentuk array.

# Merge dan Splitting

Dalam NumPy, Anda dapat menggabungkan beberapa array menjadi satu array atau membagi satu array menjadi beberapa array yang lebih kecil. Berikut beberapa konsep dasar tentang merge dan splitting pada array NumPy:

## Penggabungan (Merge): 

Anda dapat menggabungkan dua atau lebih array menggunakan fungsi numpy.concatenate(), numpy.vstack(), atau numpy.hstack().

- numpy.concatenate(): Menggabungkan array sepanjang sumbu yang diberikan.

Contoh:

In [44]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Menggabungkan array a dan b sepanjang sumbu 0
c = np.concatenate((a, b))
print(c)  # Output: [1 2 3 4 5 6]


[1 2 3 4 5 6]


numpy.vstack(): Menggabungkan array secara vertikal (sepanjang sumbu 0).

Contoh:

In [45]:
import numpy as np

a = np.array([[1, 2], 
              [3, 4]])

b = np.array([[5, 6], 
              [7, 8]])

# Menggabungkan array a dan b secara vertikal
c = np.vstack((a, b))
print(c)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


numpy.hstack(): Menggabungkan array secara horizontal (sepanjang sumbu 1).

Contoh:

In [46]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Menggabungkan array a dan b secara horizontal
c = np.hstack((a, b))
print(c)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]


[[1 2 5 6]
 [3 4 7 8]]


Pemisahan (Splitting): Anda dapat membagi satu array menjadi beberapa array yang lebih kecil menggunakan fungsi numpy.split(), numpy.vsplit(), atau numpy.hsplit().

numpy.split(): Memisahkan array menjadi beberapa array sepanjang sumbu yang diberikan.

Contoh:

In [47]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

# Memisahkan array a menjadi 3 array sepanjang sumbu 0
b = np.split(a, 3)
print(b)  # Output: [array([1, 2]), array([3, 4]), array([5, 6])]


[array([1, 2]), array([3, 4]), array([5, 6])]


numpy.vsplit(): Memisahkan array secara vertikal (sepanjang sumbu 0).

Contoh:

In [48]:
import numpy as np

a = np.array([[1, 2], 
              [3, 4], 
              [5, 6], 
              [7, 8]])

# Memisahkan array a menjadi 2 array secara vertikal
b = np.vsplit(a, 2)
print(b)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


numpy.hsplit(): Memisahkan array secara horizontal (sepanjang sumbu 1).

Contoh:

In [50]:
import numpy as np

a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8]])

# Memisahkan array a menjadi 2 array secara horizontal
b = np.hsplit(a, 2)
print(b)
# Output: [array([[1, 2],
#                [5, 6]]), 
#          array([[3, 4],
#                [7, 8]])]

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


Dengan memahami teknik penggabungan dan pemisahan ini, Anda dapat menggabungkan dan membagi array NumPy dengan mudah. Hal ini sangat penting dalam analisis data, pemrosesan sinyal, dan berbagai aplikasi lain yang melibatkan manipulasi data dalam bentuk array.

# Soal
- Atribut Array
- Operasi Matematika

## Atribut Array

***Atribut Array - shape***

Soal 1.1:<br>
Diberikan sebuah ndarray NumPy:

In [35]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Apa bentuk (shape) dari array ini?

In [36]:
print(arr.shape)

(3, 3)


Soal 1.2:<br>
Diberikan sebuah ndarray NumPy:

In [38]:
import numpy as np
arr = np.array([[[1, 2], 
                 [3, 4]], 
                 [[5, 6], 
                 [7, 8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Apa bentuk (shape) dari array ini?

In [39]:
print(arr.shape)

(2, 2, 2)


Soal 1.3:<br>
Diberikan sebuah ndarray NumPy:

In [40]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

Apa bentuk (shape) dari array ini?

In [41]:
print(arr.shape)

(5,)


***Atribut Array - ndim***

Soal 2.1:<br>
Diberikan sebuah ndarray NumPy:

In [42]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Berapa dimensi dari array ini?

In [43]:
print(arr.ndim)

2


Soal 2.2:<br>
Diberikan sebuah ndarray NumPy:

In [44]:
import numpy as np
arr = np.array([[[1, 2], 
                 [3, 4]], 
                 [[5, 6], 
                  [7, 8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Berapa dimensi dari array ini?

In [45]:
print(arr.ndim)

3


Soal 2.3:<br>
Diberikan sebuah ndarray NumPy:

In [46]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

Berapa dimensi dari array ini?

In [47]:
print(arr.ndim)

1


***Atribut Array - size***

Soal 3.1:<br>
Diberikan sebuah ndarray NumPy:

In [48]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Berapa banyak elemen dalam array ini?

In [49]:
print(arr.size)

9


Soal 3.2:<br>
Diberikan sebuah ndarray NumPy:

In [51]:
import numpy as np
arr = np.array([[[1, 2], 
                 [3, 4]], 
                [[5, 6], [7, 8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Berapa banyak elemen dalam array ini?

In [52]:
print(arr.size)

8


Soal 3.3:<br>
Diberikan sebuah ndarray NumPy:

In [53]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

Berapa banyak elemen dalam array ini?

In [54]:
print(arr.size)

5


***Atribut Array - dtype***

Soal 4.1:<br>
Diberikan sebuah ndarray NumPy:

In [55]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Apa tipe data dari elemen dalam array ini?

In [56]:
print(arr.dtype)

int32


Soal 4.2:<br>
Diberikan sebuah ndarray NumPy:

In [57]:
import numpy as np
arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
arr

array([1.1, 2.2, 3.3, 4.4, 5.5])

Apa tipe data dari elemen dalam array ini?

In [58]:
print(arr.dtype)

float64


## Operasi Matematika Array

Berikut adalah 10 soal mengenai operasi pada Array 1D dan 2D:

**Soal 1:** Buatlah array 1D dengan NumPy berisi angka 1 sampai 10. Kemudian, tambahkan setiap elemen array tersebut dengan angka 5.

**Soal 2:** Buatlah array 2D berukuran 3x3 dengan nilai dari 1 sampai 9. Lalu, kalikan setiap elemen array tersebut dengan 3.

**Soal 3:** Diberikan dua array 1D sebagai berikut: `a = np.array([1, 2, 3, 4, 5])` dan `b = np.array([6, 7, 8, 9, 10])`. Hitunglah hasil penjumlahan array `a` dan `b`.

**Soal 4:** Diberikan array 2D sebagai berikut: `A = np.array([[1, 2], [3, 4]])`. Hitunglah transpos dari array `A`.

**Soal 5:** Diberikan dua array 2D sebagai berikut: `A = np.array([[1, 2], [3, 4]])` dan `B = np.array([[5, 6], [7, 8]])`. Hitunglah hasil perkalian matrix `A` dan `B`.

**Soal 6:** Diberikan array 1D sebagai berikut: `a = np.array([1, 2, 3, 4, 5, 6])`. Ubahlah array `a` menjadi array 2D dengan 2 baris dan 3 kolom.

**Soal 7:** Buatlah array 2D berukuran 4x4 dengan nilai acak antara 0 dan 1 menggunakan NumPy.

**Soal 8:** Diberikan array 1D sebagai berikut: `a = np.array([1, 2, 3, 4, 5, 6])`. Hitunglah nilai rata-rata dari array `a`.

**Soal 9:** Diberikan array 2D sebagai berikut: `A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`. Hitunglah jumlah dari setiap baris di array `A`.

**Soal 10:** Diberikan array 2D sebagai berikut: `A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`. Hitunglah jumlah dari setiap kolom di array `A`.

Masing-masing soal di atas melibatkan operasi pada array 1D atau 2D menggunakan NumPy, termasuk operasi aritmetika dasar, transpos matriks, perkalian matriks, reshaping array, dan operasi statistik dasar.

In [61]:
#Soal 1
a = np.arange(1, 11, 1)
print(a)
b = a + 5
print ("a+b:",b)

[ 1  2  3  4  5  6  7  8  9 10]
a+b: [ 6  7  8  9 10 11 12 13 14 15]


In [64]:
#Soal 2
a = np.arange(1, 10, 1)
print('Array asli:')
print(a)

# Menggunakan reshape untuk mengubah bentuk array menjadi 2D
a_2d = a.reshape((3, 3))

print('\nArray setelah reshape:')
print(a_2d)

Array asli:
[1 2 3 4 5 6 7 8 9]

Array setelah reshape:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
# Soal 3
a = np.array([1, 2, 3, 4, 5]) 
b = np.array([6, 7, 8, 9, 10])
c = a + b
print('a+b:',c)

a+b: [ 7  9 11 13 15]


In [68]:
# Soal 4
Ar = np.array([[1, 2], [3, 4]])
B = np.transpose(Ar)
print(B)

[[1 3]
 [2 4]]


In [72]:
# Soal 5
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A @ B
print('A x B :')
print(C)

A x B :
[[19 22]
 [43 50]]


In [74]:
# Soal 6
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2,3)
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [81]:
# Soal 7
arange_2d = np.random.rand(4, 4)
print(arange_2d)

[[0.82756351 0.97851881 0.96209313 0.9238446 ]
 [0.95259747 0.13809978 0.74702158 0.3884476 ]
 [0.41123485 0.28789489 0.47769619 0.13798108]
 [0.31537417 0.64372755 0.98784169 0.45032372]]


In [83]:
# Soal 8
a = np.array([1, 2, 3, 4, 5, 6])
b = np.mean(a)
print(b)

3.5


In [84]:
# Soal 9
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Penjumlahan pada axis 1: ", A.sum(axis=1))

Penjumlahan pada axis 1:  [ 6 15 24]


In [85]:
# Soal 10
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Penjumlahan pada axis 0: ", A.sum(axis=0))

Penjumlahan pada axis 0:  [12 15 18]


**Soal 11:** Diberikan dua array 2D sebagai berikut: 
```python
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
```
Buatlah suatu array C dimana setiap elemennya merupakan hasil pengurangan elemen pada array B dengan elemen pada array A.

**Soal 12:** Diberikan array 2D sebagai berikut: `A = np.array([[2, 7, 3], [9, 5, 4]])`. Urutkan setiap baris pada array A dari nilai terkecil hingga terbesar.

**Soal 13:** Diberikan array 1D sebagai berikut: `A = np.array([5, 3, 9, 1, 8])`. Ubahlah array A menjadi array 2D berukuran 5x1.

**Soal 14:** Diberikan array 2D sebagai berikut: `A = np.array([[1, 2, 3], [4, 5, 6]])`. Hitunglah nilai median dari setiap baris pada array A.

**Soal 15:** Diberikan array 2D sebagai berikut: `A = np.array([[1, 2, 3], [4, 5, 6]])`. Lakukan normalisasi pada setiap baris pada array A, dimana setiap elemen dikurangi dengan nilai minimum dan dibagi dengan rentang nilai (nilai maksimum - nilai minimum).

Masing-masing soal di atas melibatkan operasi yang lebih kompleks pada array 1D atau 2D, termasuk pengurangan array, pengurutan nilai, reshape array, dan normalisasi nilai.

In [90]:
# Soal 11
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
C = B - A
print('B-A:')
print(C)

B-A:
[[6 6 6]
 [6 6 6]]


In [91]:
# Soal 12
A = np.array([[2, 7, 3], [9, 5, 4]])
print("Sebelum diurutkan: ", A)

B = np.sort(A)
print("Setelah diurutkan: ", B)

Sebelum diurutkan:  [[2 7 3]
 [9 5 4]]
Setelah diurutkan:  [[2 3 7]
 [4 5 9]]


In [96]:
# Soal 13
A = np.array([5, 3, 9, 1, 8])
A_2d = A[:, np.newaxis]
print(A_2d)
print(A_2d.shape)

[[5]
 [3]
 [9]
 [1]
 [8]]
(5, 1)


In [97]:
# Soal 14
A = np.array([[1, 2, 3], [4, 5, 6]])
mean_A = np.mean(A)
print("mean(A):", mean_A)

mean(A): 3.5


In [107]:
# Soal 15
A = np.array([[1, 2, 3], [4, 5, 6]])
B = (A-np.min(A))/(np.max(A)-np.min(A))
print(B)

[[0.  0.2 0.4]
 [0.6 0.8 1. ]]
